name: log_tools
description: "Logging package with detailed and human-readable logging for complex data structurea specifically made to use with Dio interceptors as well as a general purpose logging"
version: 1.0.8
repository: https://github.com/markodevcic/log_tools

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
