name: log_tools
description: "A Flutter logging package that provides detailed and human-readable logging for complex data structures, including maps and lists. It integrates with Dio interceptors to log network requests, responses, and errors in a customizable and easily readable format, while also offering general-purpose logging throughout the app."
version: 1.0.4
repository: https://github.com/markodevcic/log_tools

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
